import {
  BankField,
  FileField,
  IssuedPlaceField,
  ProvinceSelect,
  WardSelect,
} from "@/features/shared/components/form-fields";
import { generateDefaultValues, generateZodSchema } from "@/schema-validations";
import z from "zod";
export const formFields: any[] = [
  {
    title: "Thông tin cơ bản",
    fields: [
      {
        name: "agent_phone",
        label: "Số điện thoại",
        placeholder: "Nhập số điện thoại...",
        defaultValue: "",
        isDisabled: true,
        col: 4,
        isRequired: true,
        isPhone: true,
      },
      {
        name: "email",
        label: "Email (Không bắt buộc)",
        placeholder: "Nhập email...",
        type: "email",
        defaultValue: "",
        col: 4,
      },
      {
        name: "full_address",
        type: "hidden",
        col: 4,
      },
      {
        name: "agent_name",
        label: "Họ và tên",
        placeholder: "Nhập họ và tên...",
        col: 4,
        isRequired: true,
        defaultValue: "",
      },
      {
        name: "birthday",
        label: "Ngày sinh",
        placeholder: "Nhập ngày sinh...",
        type: "date",
        defaultValue: "",
        col: 4,
        isBirthday: true,
        isRequired: true,
      },
      {
        name: "gender",
        label: "Giới tính",
        placeholder: "Chọn giới tính...",
        type: "select",
        defaultValue: "Nam",
        options: [
          {
            label: "Nam",
            value: "Nam",
          },
          {
            label: "Nữ",
            value: "Nữ",
          },
        ],
        col: 4,
        isRequired: true,
      },
      {
        name: "id_bank",
        label: "Ngân hàng",
        placeholder: "Chọn ngân hàng...",
        extra: BankField,
        defaultValue: "",
        col: 8,
        isRequired: true,
      },
      {
        name: "bank_number",
        label: "Số tài khoản",
        placeholder: "Nhập số tài khoản...",
        col: 4,
        defaultValue: "",
        isRequired: true,
      },
      {
        name: "id_province",
        label: "Tỉnh/Thành phố",
        extra: ProvinceSelect,
        placeholder: "Chọn tỉnh/ thành phố...",
        col: 4,
        defaultValue: "",
        isRequired: true,
      },
      // {
      // 	name: 'id_district',
      // 	label: 'Quận/Huyện',
      // 	Component: SelectField,
      // 	type: 'select',
      // 	colControl: 'col-span-4',
      // 	options: districtOptions,
      // 	props: { options: districtOptions },
      // 	col: 4,
      // },
      {
        name: "id_commune",
        label: "Xã/Phường",
        placeholder: "Chọn xã/ phường...",
        type: "select",
        colControl: "col-span-4",
        extra: WardSelect,
        col: 4,
        defaultValue: "",
        isRequired: true,
      },
      {
        name: "address",
        label: "Số nhà tên đường",
        placeholder: "Nhập số nhà tên đường...",
        type: "text",
        col: 4,
        defaultValue: "",
        isRequired: true,
      },
    ],
  },
  {
    title: "Thông tin căn cước công dân",
    fields: [
      {
        name: "id_number",
        label: "Số CCCD",
        placeholder: "Vui lòng nhập số CCCD...",
        type: "text",
        defaultValue: "",
        isCCCD: true,
        col: 4,
        isRequired: true,
      },
      {
        name: "issued_date",
        label: "Ngày cấp",
        placeholder: "Nhập ngày cấp...",
        type: "date",
        defaultValue: "",
        col: 4,
        isRequired: true,
      },
      {
        name: "issued_place",
        label: "Nơi cấp",
        placeholder: "Vui lòng chọn nơi cấp...",
        // defaultValue: 'Bộ Công An',
        // defaultOption: 0,
        extra: IssuedPlaceField,
        col: 4,
        // isRequired: true,
        type: "hidden",
      },
      {
        name: "link_front_id",
        label: "Ảnh mặt trước",
        placeholder: "Vui lòng nhập...",
        // extra: ImageUploadField,
        // type: 'upload',
        // props: { folderType: 'cccd' },
        extra: FileField,
        type: "cccd",
        col: 4,
        isRequired: true,
      },
      {
        name: "link_back_id",
        label: "Ảnh mặt sau",
        extra: FileField,
        type: "cccd",
        // type: "upload",
        // extra: ImageUploadField,
        // props: { folderType: "cccd" },
        col: 4,
        isRequired: true,
      },
      {
        name: "link_portrait",
        type: "hidden",
        // label: 'Ảnh chân dung',
        // type: 'upload',
        // extra: ImageUploadField,
        // props: { folderType: 'avatar' },
        // isRequired: true,
        // col: 4,
      },
    ],
  },
];
const newFields = formFields.flatMap((item) => item.fields);

export const initialFormValues = generateDefaultValues(newFields);
export const formSchema: any = generateZodSchema<IFormFields>(newFields);
export type IFormFields = z.infer<typeof formSchema>;
