const ErrorCodes = [
  [1, 'Token không hợp lệ'],
  [2, 'Truy cập không hợp lệ'],
  [3, 'Cấu trúc dữ liệu không hợp lệ'],
  [4, 'Dữ liệu đã được tham chiếu, không thể thực hiện được, vui lòng kiểm tra lại'],
  [5, 'Không tìm thấy dữ liệu này trong hệ thống, vui lòng kiểm tra lại'],
  [6, 'Dữ liệu không đúng định dạng, vui lòng kiểm tra lại'],
  [7, 'Dữ liệu quá lớn so với cấu hình hệ thống, vui lòng kiểm tra lại'],
  [8, 'Đăng nhập thất bại, vui lòng kiểm tra lại'],
  [9, 'Email này đã tồn tại trong hệ thống, vui lòng kiểm tra lại'],
  [10, 'Số CCCD đã tồn tại trong hệ thống, vui lòng kiểm tra lại'],
  [11, 'Mã số thuế đã tồn tại trong hệ thống, vui lòng kiểm tra lại'],
  [12, 'Số điện thoại đã tồn tại trong hệ thống, vui lòng kiểm tra lại'],
  [13, 'Số tài khoản ngân hàng đã tồn tại trong hệ thống, vui lòng kiểm tra lại'],
  [14, 'Không thể cập nhật thông tin vào tài khoản admin, vui lòng kiểm tra lại'],
  [15, 'Dữ liệu này đã tồn tại trong hệ thống, vui lòng kiểm tra lại'],
  [16, 'Dữ liệu này đã bị khóa, vui lòng kiểm tra lại'],
  [17, 'Bạn không có quyền, vui lòng kiểm tra lại'],
  [18, 'Bạn không có quyền truy cập, vui lòng liên hệ với quản trị viên'],
  [19, 'Bạn không có quyền thao tác, vui lòng liên hệ với quản trị viên'],
  [20, 'Mật khẩu mới giống mật khẩu hiện tại, vui lòng kiểm tra lại'],
  [21, 'Mật khẩu cũ không đúng, vui lòng kiểm tra lại'],
  [22, 'Ngày sinh chưa hợp lệ vì dưới 18 tuổi, vui lòng kiểm tra lại'],
  [23, 'Thời gian nhập vào lớn hơn thời gian thực tế hiện tại, vui lòng kiểm tra lại'],
  [24, 'Link tuyển dụng đã bị khóa, vui lòng kiểm tra lại'],
  [25, 'Khởi tạo mã đăng nhập lỗi, vui lòng kiểm tra lại'],
  [26, 'Mã OTP không tìm thấy trong hệ thống, vui lòng kiểm tra lại'],
  [27, 'Mã OTP hết hạn, vui lòng kiểm tra lại'],
  [28, 'Số nhập vào hiện tại không hợp lệ (phải lớn hơn 0), vui lòng kiểm tra lại'],
  [29, 'Số hợp đồng này đã tồn tại trong hệ thống, vui lòng kiểm tra lại'],
  [30, 'Số giấy yêu cầu đã tồn tại trong hệ thống, vui lòng kiểm tra lại'],
  [31, 'Kỳ tính thưởng đã khóa, vui lòng kiểm tra lại']
]

export default ErrorCodes
