import { createFilterHook } from '~/stores';
export const useFilter = createFilterHook((state) => ({
	queryParamsState: state.queryParamsState,
	itemId: state.itemId,
	logUrl: state.logUrl,
	agentId: state.agentId,
	customerId: state.customerId,
	queryKeyState: state.queryKeyState,
	dateRange: state.dateRange,
	enableFilters: state.enableFilters,
	bonusPeriodName: state.bonusPeriodName,
	provider_code: state.provider_code,
	contract_type: state.contract_type,
	providerSelected: state.providerSelected,
	contractTypeSelected: state.contractTypeSelected,
	agentStatusSelected: state.agentStatusSelected,
	agentLevelSelected: state.agentLevelSelected,
	contractTypeList: state.contractTypeList,
	emailTypeSelected: state.emailTypeSelected,
	info: state.info,
	num_date: state.num_date,
	resetAllFilters: state.resetAllFilters,
	setFilter: state.setFilter,
}));
