import {
  BankField,
  FileField,
  IssuedPlaceField,
  PhoneField,
  ProvinceSelect,
  WardSelect,
} from "@/features/shared/components/form-fields";
import { generateDefaultValues, generateZodSchema } from "@/schema-validations";
import z from "zod";
export const formFields: any[] = [
  [
    {
      name: "parent_phone",
      label: "Số điện thoại người giới thiệu",
      placeholder: "Nhập số điện thoại...",
      type: "text",
      extra: PhoneField,
      watchName: "id_parent",
      defaultValue: "",
      isRequired: true,
      isPhone: true,
      col: 4,
    },
    {
      name: "agent_phone",
      label: "SĐT thành viên",
      placeholder: "Nhập số điện thoại...",
      type: "text",
      // extra: PhoneField,
      defaultValue: "",
      isRequired: true,
      isPhone: true,
      col: 4,
    },
    {
      name: "email",
      label: "Email (Không bắt buộc)",
      placeholder: "Nhập email...",
      type: "email",
      defaultValue: "",
      col: 4,
    },
  ],
  [
    {
      name: "id_parent",
      type: "hidden",
      defaultValue: "",
    },
    {
      name: "full_address",
      type: "hidden",
      defaultValue: "",
    },
    {
      name: "agent_name",
      label: "Tên thành viên",
      placeholder: "Nhập tên...",
      type: "text",
      defaultValue: "",
      isRequired: true,
      col: 4,
    },

    {
      name: "birthday",
      label: "Ngày sinh",
      placeholder: "Nhập ngày sinh...",
      type: "date",
      defaultValue: "",
      isBirthday: true,
      isRequired: true,
      col: 4,
    },
    {
      name: "gender",
      label: "Giới tính",
      placeholder: "Chọn giới tính",
      type: "select",
      isRequired: true,
      defaultValue: "Nam",
      options: [
        {
          label: "Nam",
          value: "Nam",
        },
        {
          label: "Nữ",
          value: "Nữ",
        },
      ],
      col: 4,
    },
    // {
    //   name: "tax",
    //   label: "Mã số thuế",
    //   placeholder: "Nhập mã số thuế...",
    //   type: "text",
    //   defaultValue: "",
    //   col: 4,
    // },
    {
      name: "id_bank",
      label: "Tên ngân hàng",
      placeholder: "Nhập tên ngân hàng...",
      extra: BankField,
      defaultValue: "",
      isRequired: true,
      col: 8,
    },
    {
      name: "bank_number",
      label: "Số tài khoản ngân hàng",
      placeholder: "Nhập số tài khoản ngân hàng...",
      type: "text",
      defaultValue: "",
      isRequired: true,
      col: 4,
    },
  ],
  [
    {
      name: "id_province",
      label: "Tỉnh/Thành phố",
      placeholder: "Chọn tỉnh/ thành phố",
      extra: ProvinceSelect,
      isRequired: true,
      isNumber: true,
      defaultValue: "",
      col: 4,
    },
    {
      name: "id_commune",
      label: "Phường/xã",
      placeholder: "Chọn phường/ xã",
      extra: WardSelect,
      isRequired: true,
      isNumber: true,
      defaultValue: "",
      col: 4,
    },
    {
      name: "address",
      label: "Số nhà tên đường",
      placeholder: "Nhập địa chỉ...",
      type: "text",
      isRequired: true,
      defaultValue: "",
      col: 4,
    },
  ],
  [
    {
      name: "id_number",
      label: "Số CCCD",
      placeholder: "Nhập số CCCD...",
      type: "text",
      defaultValue: "",
      isCCCD: true,
      isRequired: true,
      col: 4,
    },
    {
      name: "issued_date",
      label: "Ngày cấp CCCD",
      placeholder: "Nhập ngày cấp CCCD...",
      type: "date",
      isIssuedDate: true,
      defaultValue: "",
      isRequired: true,
      isBefore: true,
      col: 4,
    },
    {
      name: "issued_place",
      label: "Nơi cấp CCCD",
      placeholder: "Nhập nơi cấp CCCD...",
      extra: IssuedPlaceField,
      type: "text",
      defaultOption: 0,
      defaultValue: "Bộ Công An",
      isRequired: true,
      col: 4,
    },
    {
      name: "link_front_id",
      label: "Ảnh mặt trước",
      placeholder: "Tải lên ảnh mặt trước",
      // type: 'upload',
      // extra: ImageUploadField,
      // fieldProps: {
      // 	folderType: 'cccd',
      // },
      extra: FileField,
      type: "cccd",
      defaultValue: "",
      isRequired: true,
      col: 4,
    },
    {
      name: "link_back_id",
      label: "Ảnh mặt sau",
      placeholder: "Tải lên ảnh mặt sau",
      extra: FileField,
      type: "cccd",
      // type: 'upload',
      // extra: ImageUploadField,
      // fieldProps: {
      // 	folderType: 'cccd',
      // },
      isRequired: true,
      defaultValue: "",
      col: 4,
    },
    {
      name: "link_portrait", // link_portrait
      label: "Ảnh chân dung",
      placeholder: "Tải lên chân dung",
      extra: FileField,
      type: "avatar",
      // type: 'upload',
      // extra: ImageUploadField,
      // fieldProps: {
      // 	folderType: 'avatar',
      // },
      // isRequired: true,
      defaultValue: "",
      col: 4,
    },
  ],
];
export const agentInitialFormValues = generateDefaultValues(formFields.flat());
export const agentFormSchema: any = generateZodSchema<IFormFields>(
  formFields.flat()
);
export type IFormFields = z.infer<typeof agentFormSchema>;
