import z from "zod";
import { generateZodSchema } from "./custom-validatior";
// import { ProviderField } from '~/components/ui';
import {
  ProviderField,
  SwitchField,
} from "~/features/shared/components/form-fields";
import { FormFieldConfig } from "~/types/form-field";

const productFormFields: FormFieldConfig[] = [
  {
    name: "id_life_provider",
    label: "Nhà cung cấp",
    placeholder: "Chọn nhà cung cấp",
    extra: ProviderField,
    isRequired: true,
    defaultValue: "",
    col: 6,
  },
  // {
  //   name: "id_life_product",
  //   label: "Sản phẩm",
  //   placeholder: "Chọn sản phẩm",
  //   extra: ProductMainField,
  //   isRequired: true,
  //   defaultValue: "",
  //   col: 6,
  // },

  {
    name: "product_name",
    label: "Tên sản phẩm",
    placeholder: "Nhập tên sản phẩm...",
    type: "text",
    defaultValue: "",
    isRequired: true,
    col: 6,
  },
  {
    name: "is_main",
    label: "Sản phẩm chính",
    // placeholder: "Chọn sản phẩm",
    extra: SwitchField,
    // isRequired: true,
    defaultValue: false,
    fieldProps: {
      classNames: {
        wrapper: "flex flex-col h-full items-center gap-2",
      },
    },
    col: 6,
  },
  {
    name: "is_hide",
    label: "Ẩn sản phấm",
    type: "checkbox",
    defaultValue: false,
    col: 6,
  },
  {
    name: "xfyp_index",
    label: "Hệ số tính thưởng",
    placeholder: "Nhập hệ số tính thưởng",
    type: "number",
    isRequired: true,
    defaultValue: "1",
    col: 6,
  },
  {
    name: "xp_index",
    label: "Hệ số điểm",
    placeholder: "Nhập hệ số điểm",
    type: "number",
    isRequired: true,
    defaultValue: "1",
    col: 6,
  },
  {
    name: "xp_index_k2",
    label: "Hệ số điểm k2",
    placeholder: "Nhập hệ số điểm k2",
    type: "number",
    defaultValue: "1",
    isRequired: true,
    col: 6,
  },
  {
    name: "xp_index_k3",
    label: "Hệ số điểm k3",
    placeholder: "Nhập hệ số điểm k3",
    type: "number",
    defaultValue: "1",
    isRequired: true,
    col: 6,
  },
  {
    name: "xp_index_k4",
    label: "Hệ số điểm k4",
    placeholder: "Nhập hệ số điểm k4",
    type: "number",
    isRequired: true,
    defaultValue: "1",
    col: 6,
  },
];

const lifePolicyFields: FormFieldConfig[][] = [
  [
    {
      name: "percentage_level_1",
      label: "Thưởng AC %",
      isRequired: true,
      placeholder: "Nhập tỷ lệ thưởng AC %",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_level_2",
      label: "Thưởng AAM (%)",
      isRequired: true,
      placeholder: "Nhập tỷ lệ thưởng AAM %",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_level_3",
      label: "Thưởng AM (%)",
      isRequired: true,
      placeholder: "Nhập tỷ lệ thưởng AM %",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_level_4",
      label: "Thưởng AD (%)",
      isRequired: true,
      placeholder: "Nhập tỷ lệ thưởng AD %",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_level_5",
      label: "Thưởng TD (%)",
      isRequired: true,
      placeholder: "Nhập tỷ lệ thưởng TD %",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_level_6",
      label: "Thưởng RD (%)",
      isRequired: true,
      placeholder: "Nhập tỷ lệ thưởng RD %",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_same_level_1",
      label: "Thưởng đồng cấp AC (%)",
      isRequired: true,
      placeholder: "Nhập tỷ lệ thưởng AC %",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_same_level_2",
      label: "Thưởng đồng cấp AAM (%)",
      isRequired: true,
      placeholder: "Nhập tỷ lệ thưởng AAM %",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_same_level_3",
      label: "Thưởng đồng cấp AM (%)",
      isRequired: true,
      placeholder: "Nhập tỷ lệ thưởng AM %",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_same_level_4",
      label: "Thưởng đồng cấp AD (%)",
      isRequired: true,
      placeholder: "Nhập tỷ lệ thưởng AD %",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_same_level_5",
      label: "Thưởng đồng cấp TD (%)",
      isRequired: true,
      placeholder: "Nhập tỷ lệ thưởng TD %",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_same_level_6",
      label: "Thưởng đồng cấp RD (%)",
      isRequired: true,
      placeholder: "Nhập tỷ lệ thưởng RD %",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_finan",
      label: "Thưởng TVTC %",
      isRequired: true,
      placeholder: "Nhập % thưởng TVTC",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
  ],
  [
    {
      name: "percentage_sale_k2",
      label: "Thưởng bán hàng K2 (%)",
      isRequired: true,
      placeholder: "Nhập % thưởng bán hàng K2",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_finan_k2",
      label: "Thưởng TVTC K2 (%)",
      isRequired: true,
      placeholder: "Nhập % thưởng TVTC K2",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
  ],
  [
    {
      name: "percentage_sale_k3",
      label: "Thưởng bán hàng K3 (%)",
      isRequired: true,
      placeholder: "Nhập % thưởng bán hàng K3",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_finan_k3",
      label: "Thưởng TVTC K3 (%)",
      isRequired: true,
      placeholder: "Nhập % thưởng TVTC K3",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
  ],
  [
    {
      name: "percentage_sale_k4",
      label: "Thưởng bán hàng K4 (%)",
      isRequired: true,
      placeholder: "Nhập % thưởng bán hàng K4",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
    {
      name: "percentage_finan_k4",
      label: "Thưởng TVTC K4 (%)",
      isRequired: true,
      placeholder: "Nhập % thưởng TVTC K4",
      type: "number",
      defaultValue: "0",
      allowZero: true,
      col: 3,
    },
  ],
];
const lifeProductPolicyFields: FormFieldConfig[] = lifePolicyFields.flat();
type LifeProductPolicyFormFields = z.infer<typeof lifeProductPolicySchema>;
type LifeProductFormFields = z.infer<typeof lifeProductSchema>;
const lifeProductSchema: any =
  generateZodSchema<LifeProductFormFields>(productFormFields);
const lifeProductPolicySchema: any =
  generateZodSchema<LifeProductPolicyFormFields>(lifeProductPolicyFields);
export {
  lifePolicyFields,
  lifeProductPolicyFields,
  lifeProductPolicySchema,
  lifeProductSchema,
  productFormFields,
};
