import {
	AlarmClock,
	AlertTriangle,
	ArrowDown,
	ArrowUp,
	BarChart3,
	CalendarDays,
	Check,
	CheckSquare,
	Clipboard,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronsLeft,
	ChevronsRight,
	ChevronsUpDown,
	ChevronUp,
	Heart,
	Circle,
	Copy,
	CreditCard,
	Crop,
	DollarSign,
	Download,
	Edit,
	Eye,
	EyeOff,
	File,
	Shield,
	FileTerminal,
	Filter,
	Footprints,
	HardHat,
	Image,
	Loader2,
	LogOut,
	Menu,
	MessageSquare,
	Minus,
	Moon,
	MoreHorizontal,
	MoreVertical,
	Package,
	Plus,
	PlusCircle,
	RefreshCw,
	Search,
	Send,
	Settings,
	Shirt,
	ShoppingBag,
	ShoppingCart,
	Sliders,
	SlidersHorizontal,
	Star,
	SunMedium,
	Trash,
	Twitter,
	UploadCloud,
	User,
	Volume2,
	VolumeX,
	Pause,
	Play,
	Wallet,
	X,
	CircleHelp,
	Truck,
	Clock,
	Share2,
	Upload,
	Info,
	ThumbsUp,
	ThumbsDown,
	LogIn,
	ScrollText,
	MapPin,
	Inbox,
	Database,
	Archive,
	ArrowLeft,
	ArrowRight,
	History,
	MessageSquareMore,
	CircleCheckBig,
	Grid,
	List,
	PanelLeft,
	House,
	BookHeart,
	BookUser,
	NotebookTabs,
	FileUser,
	Scroll,
	Folder,
	FolderArchive,
	FolderKanban,
	ChartNoAxesColumnIncreasing,
	ChartNoAxesCombinedIcon,
	Bell,
	BookImage,
	UsersRound,
	Banknote,
	CircleUser,
	UserRound,
	Lock,
	Power,
	type LucideProps,
	Columns3Cog,
	OctagonAlert,
	Octagon,
	Loader,
	CircleCheck,
	FileDown,
	CalendarCheck,
	Phone,
	Recycle,
	Shuffle,
	ScanQrCode,
	FileSpreadsheet,
	Save,
	RotateCcw,
	CircleX,
	LockOpen,
	EllipsisVertical,
	ListChecks,
	CheckCheck,
	Boxes,
	BriefcaseBusiness,
	Link,
	FileSliders,
	FileText,
	GitBranch,
	ListFilter,
	Bold,
	Italic,
	Underline,
	VenusAndMars,
	Mail,
	Building,
	Venus,
	Mars,
	TrendingUp,
	TrendingDown,
	Users,
	LoaderCircle,
	MinusCircle,
} from 'lucide-react';
export const Icons = {
	house: House,
	trendingUp: TrendingUp,
	trendingDown: TrendingDown,
	bookHeart: BookHeart,
	scrollText: ScrollText,
	bell: Bell,
	scroll: Scroll,
	bold: Bold,
	italic: Italic,
	underline: Underline,
	boxes: Boxes,
	recycle: Recycle,
	shuffle: Shuffle,
	listCheck: ListChecks,
	listFilter: ListFilter,
	doubleCheck: CheckCheck,
	rotateCcw: RotateCcw,
	phone: Phone,
	save: Save,
	lock: Lock,
	unlock: LockOpen,
	lockOpen: LockOpen,
	triangle: AlertTriangle,
	excel: FileSpreadsheet,
	moreHorizontal: MoreHorizontal,
	image: Image,
	power: Power,
	columns3Cog: Columns3Cog,
	ellipsisVertical: EllipsisVertical,
	circleCheck: CircleCheck,
	fileText: FileText,
	loader: Loader,
	loaderCircle: LoaderCircle,
	folder: Folder,
	folderArchive: FolderArchive,
	folderKanban: FolderKanban,
	chartCol: ChartNoAxesColumnIncreasing,
	chartCombined: ChartNoAxesCombinedIcon,
	bookUser: BookUser,
	octagon: Octagon,
	octagonAlert: OctagonAlert,
	bookImage: BookImage,
	usersRounded: UsersRound,
	userRounded: UserRound,
	banknote: Banknote,
	circleUser: CircleUser,
	fileUser: FileUser,
	clipboardList: Clipboard,
	notebookTabs: NotebookTabs,
	sun: SunMedium,
	moon: Moon,
	star: Star,
	panelLeft: PanelLeft,
	twitter: Twitter,
	close: X,
	closeCircle: CircleX,
	spinner: Loader2,
	packageBox: Package,
	eye: Eye,
	eyeOff: EyeOff,
	list: List,
	database: Database,
	inbox: Inbox,
	archive: Archive,
	chevronLeft: ChevronLeft,
	chevronRight: ChevronRight,
	chevronsLeft: ChevronsLeft,
	chevronsRight: ChevronsRight,
	chevronUp: ChevronUp,
	chevronDown: ChevronDown,
	chevronUpDown: ChevronsUpDown,
	arrowUp: ArrowUp,
	arrowDown: ArrowDown,
	arrowLeft: ArrowLeft,
	arrowRight: ArrowRight,
	menu: Menu,
	venusAndMars: VenusAndMars,
	venus: Venus,
	mars: Mars,
	heart: Heart,
	mail: Mail,
	building: Building,
	verticalThreeDots: MoreVertical,
	horizontalThreeDots: MoreHorizontal,
	verticalSliders: Sliders,
	horizontalSliders: SlidersHorizontal,
	history: History,
	circle: Circle,
	circleCheckBig: CircleCheckBig,
	clipboard: Clipboard,
	circleHelp: CircleHelp,
	check: Check,
	checkSquare: CheckSquare,
	add: Plus,
	addCircle: PlusCircle,
	scanQrCode: ScanQrCode,
	remove: Minus,
	minusCircle: MinusCircle,
	view: Eye,
	hide: EyeOff,
	trash: Trash,
	edit: Edit,
	more_vertical: MoreVertical,
	crop: Crop,
	reset: RefreshCw,
	send: Send,
	copy: Copy,
	link: Link,
	gitBranch: GitBranch,
	tool: FileSliders,
	download: Download,
	warning: AlertTriangle,
	briefcaseBusiness: BriefcaseBusiness,
	search: Search,
	filter: Filter,
	alarm: AlarmClock,
	calendar: CalendarDays,
	calendarCheck: CalendarCheck,
	user: User,
	users: Users,
	login: LogIn,
	order: ScrollText,
	terminal: FileTerminal,
	settings: Settings,
	logout: LogOut,
	volume: Volume2,
	volumeMute: VolumeX,
	message: MessageSquare,
	messageMore: MessageSquareMore,
	billing: CreditCard,
	wallet: Wallet,
	dollarSign: DollarSign,
	cart: ShoppingCart,
	shoppingBag: ShoppingBag,
	product: Package,
	store: ShoppingBag,
	chart: BarChart3,
	upload: Upload,
	info: Info,
	thumbUp: ThumbsUp,
	thumbDown: ThumbsDown,
	uploadClound: UploadCloud,
	placeholder: Image,
	clothing: Shirt,
	shoes: Footprints,
	accessories: HardHat,
	pause: Pause,
	play: Play,
	truck: Truck,
	creditCard: CreditCard,
	mapPin: MapPin,
	shield: Shield,
	clock: Clock,
	refresh: RefreshCw,
	file: File,
	fileDown: FileDown,
	share: Share2,
	grid: Grid,

	emptyData: ({ ...props }: LucideProps) => (
		<svg viewBox="0 0 66 66" xmlns="http://www.w3.org/2000/svg" {...props}>
			<path d="M17 6.33228L9 16.9989V54.3323C9 55.7468 9.5619 57.1033 10.5621 58.1035C11.5623 59.1037 12.9188 59.6656 14.3333 59.6656H51.6667C53.0811 59.6656 54.4377 59.1037 55.4379 58.1035C56.4381 57.1033 57 55.7468 57 54.3323V16.9989L49 6.33228H17Z" />
			<path d="M9 16.9999H57" />
			<path d="M43.6663 27.6677C43.6663 30.4967 42.5425 33.2098 40.5421 35.2102C38.5418 37.2106 35.8286 38.3344 32.9997 38.3344C30.1707 38.3344 27.4576 37.2106 25.4572 35.2102C23.4568 33.2098 22.333 30.4967 22.333 27.6677" />
		</svg>
	),
};
